#!/system/bin/sh
#
# Copyright (c) Leonard Luangga


#drop caches to free some memory
sync
echo 3 > /proc/sys/vm/drop_caches
sleep 1
echo 1 > /proc/sys/vm/drop_caches
#free pagecache. dentries and inodes will be managed by /proc/sys/vm/vfs_cache_pressure


#remove cache, tmp, and unused files
rm -f /cache/*.apk
rm -f /cache/*.tmp
rm -f /data/dalvik-cache/*.apk
rm -f /data/dalvik-cache/*.tmp

if [ -e /data/system/userbehavior.db ]
then
  rm -f /data/system/userbehavior.db
fi

if [ -d /data/system/usagestats ]
then
  chmod 400 /data/system/usagestats
fi

if [ -d /data/system/appusagestats ]
then
  chmod 400 /data/system/appusagestats
fi


#remove main log
if [ -e /dev/log/main ]
then
  rm -f /dev/log/main
fi


# cache handler
# Copyright (c) slaid480

CACHESIZE=$(df -k /cache | tail -n1 | tr -s ' ' | cut -d ' ' -f2)
if [ $CACHESIZE -gt 80000 ]
then
  echo "Large cache detected, moving dalvik-cache to /cache"
	if [ ! -d /cache/dalvik-cache ]
  then
    busybox rm -rf /cache/dalvik-cache /data/dalvik-cache
    mkdir /cache/dalvik-cache /data/dalvik-cache
  fi

  busybox chown 1000:1000 /cache/dalvik-cache
  busybox chmod 0771 /cache/dalvik-cache

  # bind mount dalvik-cache so we can still boot without the sdcard
  busybox mount -o bind /cache/dalvik-cache /data/dalvik-cache
  busybox chown 1000:1000 /data/dalvik-cache
  busybox chmod 0771 /data/dalvik-cache
fi
