#!/system/bih/sh
#
# Copyright (c) Leonard Luangga


#internet speed tweaks
echo 0 > /proc/sys/net/ipv4/tcp_timestamps
echo 0 > /proc/sys/net/ipv4/tcp_tw_recycle
echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
echo 1 > /proc/sys/net/ipv4/tcp_sack
echo 1 > /proc/sys/net/ipv4/tcp_window_scaling
echo 5 > /proc/sys/net/ipv4/tcp_keepalive_probes
echo 20 > /proc/sys/net/ipv4/tcp_keepalive_intvl
echo 1800 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 30 > /proc/sys/net/ipv4/tcp_fin_timeout
echo 404480 > /proc/sys/net/core/wmem_max
echo 404480 > /proc/sys/net/core/rmem_max
echo 256960 > /proc/sys/net/core/rmem_default
echo 256960 > /proc/sys/net/core/wmem_default
echo 4096 16384 404480 > /proc/sys/net/ipv4/tcp_wmem
echo 4096 87380 404480 > /proc/sys/net/ipv4/tcp_rmem


#optimize build.prop
#setprop ro.ril.hsxpa 2 #HSDPA/UMTS? I think this one gonna drain more and more battery
#setprop ro.ril.hsxpa 1 #HSDPA only? hmm I think this one drain more battery than UMTS only
#setprop ro.ril.hsxpa 0 #UMTS only? slower but I think this one drain less battery
setprop ro.ril.hsxpa 0
setprop ro.ril.gprsclass 10
setprop ro.ril.hsupa.category 6
setprop ro.ril.hsdpa.category 8
setprop ro.ril.hep 1
setprop ro.ril.enable.dtm 1
setprop ro.ril.enable.a53 1
setprop ro.ril.enable.3g.prefix 1
setprop net.tcp.buffersize.default 4096,87380,256960,4096,16384,256960
setprop net.tcp.buffersize.wifi 4096,87380,256960,4096,16384,256960
setprop net.tcp.buffersize.umts 4096,87380,256960,4096,16384,256960
setprop net.tcp.buffersize.edge 4096,87380,256960,4096,16384,256960
setprop net.tcp.buffersize.gprs 4096,87380,256960,4096,16384,256960
