#!/system/bih/sh
#
# Copyright (c) Leonard Luangga


#battery tweaks (sleepers)
mount -t debugfs none /sys/kernel/debug
echo NO_NEW_FAIR_SLEEPERS > /sys/kernel/debug/sched_features
echo NO_NORMALIZED_SLEEPERS > /sys/kernel/debug/sched_features
umount /sys/kernel/debug

#battery tweaks (vm)
echo 0 > /proc/sys/vm/laptop_mode
echo 1000 > /proc/sys/vm/dirty_expire_centisecs
echo 1500 > /proc/sys/vm/dirty_writeback_centisecs
echo 30 > /proc/sys/vm/dirty_ratio
echo 15 > /proc/sys/vm/dirty_background_ratio


#vm management tweaks
echo 0 > /proc/sys/vm/panic_on_oom
echo 0 > /proc/sys/vm/overcommit_memory
echo 0 > /proc/sys/vm/oom_kill_allocating_task
echo 3 > /proc/sys/vm/page-cluster
echo 10 > /proc/sys/vm/swappiness
echo 60 > /proc/sys/vm/vfs_cache_pressure
#vfs_cache_presure's default value=100. low value can cause memory leak, high value drains more battery

echo 2896 > /proc/sys/vm/min_free_kbytes
#default value for /proc/sys/vm/min_free_kbytes
# RAM     min_free_kbytes
# 16MB		512k
# 32MB		724k
# 64MB		1024k
# 128MB		1448k
# 256MB		2048k
# 512MB		2896k
# 1024MB	4096k
# 2048MB	5792k
# 4096MB	8192k
# 8192MB	11584k


#kernel tweaks
#echo 0 > /proc/sys/kernel/panic_on_oops #set this to 0 to prevent random reboots
echo 0 > /proc/sys/kernel/panic
echo 0 > /proc/sys/kernel/panic_on_oops
echo 30 > /proc/sys/fs/lease-break-time
echo 256 > /proc/sys/kernel/msgmni
echo 8192 > /proc/sys/kernel/msgmax
echo 16384 > /proc/sys/kernel/msgmnb
echo 4096 > /proc/sys/kernel/shmmni
echo 300 32000 64 256 > /proc/sys/kernel/sem
echo 4096 > /proc/sys/kernel/threads-max

if [ -e /proc/sys/kernel/sched_rt_period_us ]
then
  echo 1000000 > /proc/sys/kernel/sched_rt_period_us
fi

if [ -e /proc/sys/kernel/sched_rt_runtime_us ]
then
  echo 950000 > /proc/sys/kernel/sched_rt_runtime_us
fi

if [ -e /proc/sys/kernel/sched_min_granularity_ns ]
then
	echo 200000 > /proc/sys/kernel/sched_min_granularity_ns
fi

if [ -e /proc/sys/kernel/sched_latency_ns ]
then
	echo 400000 > /proc/sys/kernel/sched_latency_ns
fi

if [ -e /proc/sys/kernel/sched_wakeup_granularity_ns ]
then
	echo 100000 > /proc/sys/kernel/sched_wakeup_granularity_ns
fi

if [ -e /proc/sys/kernel/hung_task_timeout_secs ]
then
	echo 45 > /proc/sys/kernel/hung_task_timeout_secs
fi


#lowmemorykiller tweaks
if [ -e /sys/module/lowmemorykiller/parameters/adj ]
then
	echo "0,1,2,4,6,15" > /sys/module/lowmemorykiller/parameters/adj
fi

if [ -e /sys/module/lowmemorykiller/parameters/minfree ]
then
	echo "2304,4608,6912,11520,13824,16128" > /sys/module/lowmemorykiller/parameters/minfree
fi


# from V8 TurboBoost by GadgetCheck
# configure touchscreen sensitivity
echo 7035 > /sys/class/touch/switch/set_touchscreen;
echo 8002 > /sys/class/touch/switch/set_touchscreen;
echo 11000 > /sys/class/touch/switch/set_touchscreen;
echo 13060 > /sys/class/touch/switch/set_touchscreen;
echo 14005 > /sys/class/touch/switch/set_touchscreen;
